---
version: 2.1

orbs:
  base-packages: twdps/base-packages@dev:<<pipeline.git.revision>>

globals:
  - &context orb-publishing

jobs:

  test pinned version installs:
    machine:
      image: ubuntu-2204:current
    resource_class: medium
    steps:
      - checkout
      - base-packages/install:
          op-version: 2.31.1
          teller-version: 1.5.6
          vault-version: 1.15.4-1
          bats-version: 1.5.0
          cosign-version: 2.1.1
          grype-version: 0.91.0
          hadolint-version: 2.12.0
          oras-version: 0.14.0
          snyk-version: 1.103.0
          syft-version: 0.81.0
          trivy-version: 0.32.0
      - run:
          name: confirm installed version for available packages
          command: |
            set -exo pipefail
            op --version | grep "2.31.1"
            teller version | grep "1.5.6"
            vault version | grep "1.15.4"
            bats --version | grep "1.5.0"
            cosign version | grep "2.1.1"
            grype --version | grep "0.91.0"
            hadolint --version | grep "2.12.0"
            oras version | grep "0.14.0"
            snyk --version | grep "1.103.0"
            syft version | grep "0.81.0"
            trivy version | grep "0.32.0"

  test latest version installs:
    machine:
      image: ubuntu-2204:current
    resource_class: medium
    steps:
      - checkout
      - base-packages/install:
          op-version: latest
          vault-version: latest
          bats-version: latest
          cosign-version: latest
          grype-version: latest
          hadolint-version: latest
          oras-version: latest
          snyk-version: latest
          syft-version: latest
          trivy-version: latest
      - run:
          name: confirm installed version for available packages
          command: |
            set -exo pipefail
            op --version
            op --help | grep "Usage:"
            vault version
            vault --help | grep "Usage:"
            bats --version
            bats --help | grep "Usage:"
            cosign version
            cosign --help | grep "Usage:"
            grype --version
            grype --help | grep "Usage:"
            hadolint --version
            hadolint --help | grep "Usage:"
            oras version
            oras --help | grep "Usage:"
            snyk --version
            snyk --help | grep "How to get started"
            syft version
            syft --help | grep "Usage:" 
            trivy version
            trivy --help | grep "Usage:"

workflows:

  integration tests:
    jobs:
      - test pinned version installs:
          context: *context
      - test latest version installs:
          context: *context
